server:
  port: 8088
  servlet:
    context-path: /blogapi

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    #    password:
    jedis.pool.max-idle: 100
    jedis.pool.max-wait: -1ms
    jedis.pool.min-idle: 2
    timeout: 2000ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/msblogapp?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  batch:
    jdbc:
      table-prefix: blog_
#  redis:
#    database: 0
#    # Redis服务器地址 写你的ip
#    host: 127.0.0.1
#    # Redis服务器连接端口
#    port: 6379
#    # Redis服务器连接密码（默认为空）
#    # 连接池最大连接数（使用负值表示没有限制  类似于mysql的连接池
#    pool:
#      max-active: 100 #连接池最大连接数（负值表示没有限制）
#      max-wait: 3000 #连接池最大阻塞等待时间（负值表示没有限制）
#      max-idle: 200 #连接池最大空闭连接数
#      min-idle: 50 #连接汉最小空闲连接数
#      timeout: 6000 #连接超时时间（毫秒）


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0
      table-prefix: blog_
#      logic-delete-field: deleted
#        logic-delete-value: 1
        # 逻辑已删除值(默认为 1)
#        logic-not-delete-value: 0
        # 逻辑未删除值(默认为 0)


